programs/views.py
import json

from flask import Blueprint, request, redirect, flash, g, render_template, url_for, session, jsonify

from .models import Program, Trigger, Event, Condition, Loop, Block, Link, ConditionLink

from decorators import login_required

import re

matcher = re.compile(r"^.*{{ (.*) }}.*$")

blueprint = Blueprint("programs", __name__, url_prefix="/program")

ARGS_MAPPINGS = {
            'rss': {
                    "url": "string"
                },
            'sms': {
                    "phone": "string",
                    "message": "string"
                },
            'twitter': {
                    "handle": "string"
                },
            'if': {
                    'inner': 'string',
                    'oper': 'string',
                    'outer': 'string'
                }
        }

RESULTS_MAPPINGS = {
            'rss': {
                    "url": "string",
                    "title": "string",
                    "text": "string"
                },
            'twitter': {
                    'handle': 'string',
                    'body': 'string',
                    'date': 'string'
                }
        }

@blueprint.route("/editor/")
@login_required
def editor():
    return render_template("editor.html", user=g.user)

@blueprint.route("/editor/<int:id>/")
@login_required
def edit(id):
    p = Program.get(Program.id == id)
    return render_template("editor.html", user=g.user, prog_id=id, name=p.name or "", json=p.json)

@blueprint.route("/delete/<int:id>/")
@login_required
def delete(id):
    p = Program.get(Program.id == id)
    if (g.user == p.owner):
        flash("Program deleted!", "success")
        p.delete_instance()
    else:
        flash("You do not have permission to delete this program!", "error")
    return redirect(url_for("index"))


@blueprint.route("/save/", methods=["POST"])
@login_required
def save():
    raw = request.form.get("program")
    prgrm = json.loads(raw)
    p = Program.create(owner=g.user, name=request.form.get("name", None), json=raw)
    process_program(prgrm, p)
    return jsonify({"success": True})

def process_program(prgrm, p, old_blocks=[]):
    db_blocks = []
    for block in prgrm:
        if block["type"] == "trigger":
            t = Trigger.create(trigger_type=block["name"], args=formatted_args(block), results=formatted_results(block))
            b = Block.create(program=p, block_type="t", trigger=t)
            db_blocks.append(b)
        elif block["type"] == "event":
            e = Event.create(args=formatted_args(block, db_blocks + old_blocks), action=block["name"])
            b = Block.create(program=p, block_type="e", event=e)
            db_blocks.append(b)
        elif block["type"] == "conditional":
            in_args = process_value(block["values"]["left"], db_blocks + old_blocks)
            check = block["values"]["operation"]
            out_args = process_value(block["values"]["right"], db_blocks + old_blocks)
            c = Condition.create(in_val=in_args, check=check, out_val=out_args)
            b = Block.create(program=p, block_type="c", condition=c)
            inner_b = process_program(block["inner"], p, db_blocks + old_blocks)
            outer_b = process_program(block["outer"], p, db_blocks + old_blocks)
            cl = ConditionLink.create(source=c, inner=inner_b, outer=outer_b)
            db_blocks.append(b)
    for i, val in enumerate(db_blocks[:-1]):
        l = Link.create(source=db_blocks[i], destination=db_blocks[i+1])
    return db_blocks[0]

def process_value(val, all_blocks=[]):
    match = matcher.match(val)
    if match:
        new_val = match.group(1)
        block_type = new_val.split(".")[0]
        val_block = None
        for b in all_blocks:
            if b.block_type == "t":
                if b.trigger.trigger_type == block_type:
                    val_block = b
            elif b.block_type == "e":
                if b.event.action == block_type:
                    val_block = b
        get_val = new_val.split(".")[1]
        val = re.sub("{{.*}}", "{" + "id_{}[{}]".format(val_block.id, get_val)+ "}", val)
    return val

def formatted_args(block, all_blocks=[]):
    args = "["
    for key in ARGS_MAPPINGS[block["name"]]:
        args += "('{}', '{}', '{}'), ".format(process_value(block["values"][key], all_blocks), key, ARGS_MAPPINGS[block["name"]][key])
    args = args[:-2]
    args += "]"
    return args

def formatted_results(block):
    results = "["
    for key in RESULTS_MAPPINGS[block["name"]]:
        results += "('{}', '{}'), ".format(key, RESULTS_MAPPINGS[block["name"]][key])
    results = results[:-2]
    results += "]"
    return results

settings/__init__.py
DEBUG = True

MODULES = [
        "users",
        "programs",
        ]

MODELS = [
        ("users.models", "User"),
        ("programs.models", "Program"),
        ("programs.models", "Trigger"),
        ("programs.models", "Event"),
        ("programs.models", "Condition"),
        ("programs.models", "Loop"),
        ("programs.models", "Block"),
        ("programs.models", "Link"),
        ("programs.models", "ConditionLink"),
        ]

SECRET_KEY = "secret"

users/views.py
from flask import Blueprint, request, redirect, flash, g, render_template, url_for, session

from .models import User

from utils import get_current_user

blueprint = Blueprint("users", __name__, url_prefix="/user")

@blueprint.route("/login/", methods=["GET", "POST"])
def login():
    if g.user:
        return redirect(url_for("index"))
    if request.method == "POST":
        error = False
        try:
            u = User.get(User.email == request.form.get("email", ""))
            if not u.password.check_password(request.form.get("password", "")):
                error = True
        except User.DoesNotExist:
            error = True
        if error:
            flash("Failed login!", "error")
            return render_template("login.html", email=request.form.get("email",""))
        else:
            session["uid"] = u.id
            session["logged_in"] = True
            return redirect(request.args.get("next", url_for("index")))
    else:
        return render_template("login.html")

@blueprint.route("/register/", methods=["GET", "POST"])
def register():
    if g.user:
        return redirect(url_for("index"))
    if request.method == "POST":
        name = request.form.get("name", None)
        email = request.form.get("email", None)
        password = request.form.get("password", None)
        confirm = request.form.get("confirm", None)
        if not name or not email or not password:
            flash("Please fill out all of the fields!", "error")
            return redirect(url_for("users.register"))
        if password != confirm:
            flash("Confirmation does not match password!", "error")
            return redirect(url_for("users.register"))
        try:
            u = User.get(User.email == email)
            flash("An account with this email already exists!", "error")
            return redirect(url_for("users.login"))
        except User.DoesNotExist:
            pass
        u = User.create(name=name, email=email, password=password)
        flash("Your account has been created!", "success")
        session["uid"] = u.id
        session["logged_in"] = True
        return redirect(url_for("index"))
    else:
        return render_template("register.html")

@blueprint.route("/logout/")
def logout():
    session["uid"] = -1
    session["logged_in"] = False
    return redirect(url_for("index"))

@blueprint.route("/settings", methods=["GET","POST"])
def settings():
    return redirect(url_for("index"))
    # No use for a real settings page
    # return render_template("settings.html", user=g.user)

@blueprint.before_app_request
def set_user():
    g.user = get_current_user()

templates/base-nav.html
{% extends "base.html" %}

{% block nav %}
    <nav class="navbar navbar-toggleable-md navbar-dark">
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <a class="navbar-brand" href="/"> Automate</a>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{{ url_for('index') }}">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('programs.editor') }}">Editor</a>
                </li>
            </ul>
            <ul class="navbar-nav navbar-right">
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('users.settings') }}"><i class="fa fa-user"></i> {{ user.name }}</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('users.logout') }}">Logout</a>
                </li>
            </ul>
        </div>
    </nav>
{% endblock %}

templates/base.html
<!doctype html>
<html>
    <head>
        <title>Automate</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}">
        {% block css %}
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/css/tether.css" integrity="sha256-XlckdtWgpo4xmVoJR0BgtatbV/UpLTiOE+UBfRGFutg=" crossorigin="anonymous" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha256-rr9hHBQ43H7HSOmmNkxzQGazS/Khx+L8ZRHteEY1tQ4=" crossorigin="anonymous" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" integrity="sha256-eZrrJcwDc/3uDhsdt61sL2oOBY362qM3lon1gyExkL0=" crossorigin="anonymous" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/messenger/1.5.0/css/messenger.min.css" integrity="sha256-s9TkqCOAYSX0OL0SFkn9uuNWdDLIXKMUV0ZICMxDBC8=" crossorigin="anonymous" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/messenger/1.5.0/css/messenger-theme-flat.css" integrity="sha256-VkjwgxP9YQTZwAfP89z6hhs22SJo4g+uGhUJxSLIzb4=" crossorigin="anonymous" />
        <link rel="stylesheet" href="{{ url_for('static',filename='css/base.css')}}">
        {% endblock %}
        {% block js %}
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js" integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4=" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.js" integrity="sha256-jVfFb7AbGi7S/SLNl8SB4/MYaf549eEs+NlIWMoARHg=" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha256-+kIbbrvS+0dNOjhmQJzmwe/RILR/8lb/+4+PUNVW09k=" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/messenger/1.5.0/js/messenger.min.js" integrity="sha256-BnQeGKS32Pt/mkLkk742fNXjfLN5/4OOd3L9PAf5d3s=" crossorigin="anonymous"></script>
        <script src="{{ url_for('static',filename='js/base.js')}}"></script>
        {% endblock %}
        {% with messages = get_flashed_messages(with_categories=True) %}
            {% if messages %}
            <script>
                $(document).ready(function() {
                    {% for category, message in messages %}
                        {% if category == "error" %}
                            Messenger().error("{{ message }}");
                        {% elif category == "success" %}
                            Messenger().success("{{ message }}");
                        {% else %}
                            Messenger().info("{{ message }}");
                        {% endif %}
                    {% endfor %}
                });
            </script>
            {% endif %}
        {% endwith %}
    </head>
    <body>
        {% block nav %}{% endblock %}
        <div id="content">
            {% block content %}{% endblock %}
        </div>
    </body>
</html>

templates/editor.html
{% extends "base-nav.html" %}

{% block css %}
    {{ super() }}
    <style>
    </style>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/editor.css') }}">
{% endblock %}

{% block js %}
    {{ super() }}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/fabric.js/1.7.9/fabric.min.js" integrity="sha256-D5qjlhHft5LNta9Zzei8iPWEAGyIQt6JkWftlBA81yk=" crossorigin="anonymous"></script>
    <script src="{{ url_for('static', filename='js/editor.js') }}"></script>
    <script>
    var save_endpoint = "{{ url_for('programs.save') }}";
    var program_id = {{ prog_id|default("-1") }};
    try {
        var program_save = "{{ json|replace('"', '\\"')|safe }}";
    }
    catch (e) {
        var program_save = "";
    }
    </script>
{% endblock %}

{% block content %}
    <div id="picker">
        <div id="picker-list">
            <h3>Triggers</h3>
            <div id="triggers"></div>
            <h3>Events</h3>
            <div id="events"></div>
            <h3>Conditionals</h3>
            <div id="conditionals"></div>
            <hr />
            <span id="default" class="tool active"><i class="fa fa-fw fa-mouse-pointer"></i></span>
            <span id="arrow" class="tool"><i class="fa fa-fw fa-expand"></i></span>
            <span id="delete" class="tool"><i class="fa fa-fw fa-trash-o"></i></span>
            <span id="noaction" class="tool"><i class="fa fa-fw fa-ban"></i></span>
            <span id="filter" class="tool pull-right"><i class="fa fa-fw fa-filter"></i></span>
            <hr />
            <input type="text" id="name" placeholder="Name" style="max-width: 150px; display: inline-block; border-radius: 25px" value="{{ name|default('') }}" class="form-control" /> <button id="save" class="btn btn-success"><i class="fa fa-floppy-o"></i> Save</button>
        </div>
        <i class="fa fa-times close-icon" id="picker-close"></i>
    </div>
    <canvas id="editor"></canvas>

    <!-- Modal -->
    <div class="modal fade" id="conditional-modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Edit Block</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="button" class="btn btn-primary save-modal">Save changes</button>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/index.html
{% extends "base-nav.html" %}

{% block js %}
    {{ super() }}
    <script src="http://cdn.jsdelivr.net/particles.js/2.0.0/particles.min.js"></script>
    <script src="{{ url_for('static', filename='js/home.js') }}"></script>
{% endblock %}

{% block css %}
    {{ super() }}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/home.css') }}">
{% endblock %}

{% block content %}
<div id="particles-js"></div>
<h3>Your Programs</h3>
<div id="home" class="container main">
    {% if not programs %}
        <div class="noprog">
            <h5>It looks like you haven't made any programs yet!</h5>
            <a href="{{ url_for('programs.editor') }}" class="btn btn-primary">Start a program!</a>
        </div>
    {% else %}
        <div class="row">
        {% for prog in programs %}
            <div class="program col-sm-5">
                <h4>{{ prog.name if prog.name is not none else 'Unnamed Program' }}<h4>
                <a href="{{ url_for('programs.edit', id=prog.id) }} " class="btn btn-primary">Edit</a>
                <a href="{{ url_for('programs.delete', id=prog.id) }} " class="btn btn-danger">Delete</a>
            </div>
        {% endfor %}
        </div>
    {% endif %}
</div>
{% endblock %}

templates/login.html
{% extends "base.html" %}

{% block css %}
    {{ super() }}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/login.css')}}">
{% endblock %}

{% block js %}
    {{ super() }}
    <script src="http://cdn.jsdelivr.net/particles.js/2.0.0/particles.min.js"></script>
    <script src="{{ url_for('static', filename='js/login.js') }}"></script>
{% endblock %}

{% block content %}
<div id="particles-js"></div>
<div class="container">
<div id="login" class="box clearfix main">
    <form method="POST">
        <h2>Automate</h2>
        <div class="form-group">
            <div class="input-group">
                <input id="id_email" name="email" type="email" class="form-control" placeholder="Email" value="{{ email }}"/>
            </div>
        </div>
        <div class="form-group">
            <div class="input-group">
                <input id="id_password" name="password" type="password" class="form-control" placeholder="Password" />
            </div>
        </div>
        <button type="submit" class="btn btn-primary">Login</button>
        <a href="{{ url_for('users.register') }}" id="footer-text">Don't have an account? Click here!</a>
    </form>
</div>
<div class="footer"></div>
</div>
{% endblock %}

templates/register.html
{% extends "base.html" %}

{% block css %}
    {{ super() }}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/login.css')}}">
{% endblock %}

{% block js %}
    {{ super() }}
    <script src="http://cdn.jsdelivr.net/particles.js/2.0.0/particles.min.js"></script>
    <script src="{{ url_for('static', filename='js/login.js') }}"></script>
{% endblock %}

{% block content %}
<div id="particles-js"></div>
<div class="container">
<div id="register" class="box clearfix main">
    <form method="POST">
        <h2>Register</h2>
        <div class="form-group">
            <div class="input-group">
                <input id="id_name" name="name" type="name" class="form-control" placeholder="Name" />
            </div>
        </div>
        <div class="form-group">
            <div class="input-group">
                <input id="id_email" name="email" type="email" class="form-control" placeholder="Email" />
            </div>
        </div>
        <div class="form-group">
            <div class="input-group">
                <input id="id_password" name="password" type="password" class="form-control" placeholder="Password" />
            </div>
        </div>
        <div class="form-group">
            <div class="input-group">
                <input id="id_confirm" name="confirm" type="password" class="form-control" placeholder="Confirm Password" />
            </div>
        </div>
        <button type="submit" class="btn btn-primary">Register</button>
        <a href="{{ url_for('users.login') }}" id="footer-text">Already have an account? Click here!</a>
    </form>
</div>
<div class="footer"></div>
</div>
{% endblock %}

templates/settings.html
{% extends "base-nav.html" %}

{% block js %}
    {{ super() }}
    <script src="http://cdn.jsdelivr.net/particles.js/2.0.0/particles.min.js"></script>
    <script src="{{ url_for('static', filename='js/home.js') }}"></script>
{% endblock %}

{% block css %}
    {{ super() }}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/home.css') }}">
{% endblock %}

{% block content %}
<div id="particles-js"></div>
<h3>Settings</h3>
<div id="settings" class="container main">
    <p>Email: {{ user.email }}</p>
    <h4>Change password</h4>
</div>
{% endblock %}